"""Execution Engine — Stage 2 parent agent (brief + variants + outreach)."""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from typing import Any

from app.models import score_to_level
from app.tools.source_validator import filter_and_rank_sources

from .ab_variant_agent import run_ab_variant_agent
from .content_agent import run_content_agent
from .grounding import enforce_execution_grounding
from .outreach_formatter import run_outreach_formatter

AGENT_ID = "execution-engine"
AGENT_NAME = "Execution Engine"


def _dedupe_strings(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        normalized = " ".join(value.lower().split()).strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        out.append(value.strip())
    return out


async def run(ctx: dict[str, Any]) -> dict[str, Any]:
    research_outputs = ctx.get("research_outputs") or []

    grounding_context = ""
    if research_outputs:
        parts = []
        for o in research_outputs:
            domain = (o.get("domain") or "research").upper()
            facts = " | ".join((o.get("facts") or [])[:4])
            interpretation = " | ".join((o.get("interpretation") or [])[:2])
            parts.append(f"[{domain}]\nFACTS: {facts}\nINTERPRETATION: {interpretation}")
        grounding_context = "\n\n".join(parts)

    prior_parts = [p for p in [ctx.get("prior_context"), grounding_context] if p]
    enriched_ctx = {**ctx, "prior_context": "\n\n---\n".join(prior_parts) if prior_parts else None}

    content_result, variant_result = await asyncio.gather(
        run_content_agent(enriched_ctx),
        run_ab_variant_agent(enriched_ctx),
        return_exceptions=True,
    )

    input_variants: list[dict[str, Any]] = []
    if not isinstance(variant_result, BaseException):
        input_variants = variant_result.get("variants") or []

    outreach_result: dict[str, Any] | None = None
    try:
        outreach_result = await run_outreach_formatter(enriched_ctx, input_variants)
    except Exception:
        outreach_result = None

    all_sources: list[dict[str, Any]] = []
    if not isinstance(content_result, BaseException):
        all_sources.extend(content_result.get("sources") or [])
    if not isinstance(variant_result, BaseException):
        all_sources.extend(variant_result.get("sources") or [])
    if outreach_result:
        all_sources.extend(outreach_result.get("sources") or [])
    all_sources = filter_and_rank_sources(all_sources, 12)

    all_facts = _dedupe_strings(
        ([] if isinstance(content_result, BaseException) else (content_result.get("facts") or []))
        + ([] if isinstance(variant_result, BaseException) else (variant_result.get("facts") or []))
    )[:6]

    all_interpretation = _dedupe_strings(
        ([] if isinstance(content_result, BaseException) else (content_result.get("interpretation") or []))
        + ([] if isinstance(variant_result, BaseException) else (variant_result.get("interpretation") or []))
    )[:4]

    scores: list[float] = []
    if not isinstance(content_result, BaseException):
        scores.append(float(content_result.get("confidenceScore", 0)))
    if not isinstance(variant_result, BaseException):
        scores.append(float(variant_result.get("confidenceScore", 0)))
    if outreach_result:
        scores.append(float(outreach_result.get("confidenceScore", 0)))

    avg_score = sum(scores) / len(scores) if scores else 0.4
    confidence = score_to_level(avg_score)

    product = ctx.get("product", "the product")
    if not isinstance(content_result, BaseException) and content_result.get("brief"):
        brief = content_result["brief"]
    else:
        brief = {
            "objective": f"Campaign for {product}",
            "targetAudience": "VP Sales / Head of Growth at Series B+ SaaS",
            "painPoints": [],
            "keyMessagingAngles": [],
            "variantsSummary": "Variants generated by A/B agent",
            "channelStrategy": "Cold email + LinkedIn",
            "successMetrics": ["reply rate > 4%"],
            "nextSteps": ["Run A/B test", "Analyse reply sentiment after 72h"],
        }

    merged_variants = (
        outreach_result.get("enrichedVariants") or input_variants
        if outreach_result and outreach_result.get("enrichedVariants")
        else input_variants
    )
    variants = enforce_execution_grounding(merged_variants, research_outputs, product)
    deployment = (outreach_result or {}).get("deployment") or []

    return {
        "agentId": AGENT_ID,
        "domain": "execution-engine",
        "artifactType": "execution-plan",
        "confidence": confidence,
        "confidenceScore": avg_score,
        "facts": all_facts,
        "interpretation": all_interpretation,
        "sources": all_sources,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "variants": variants,
        "brief": brief,
        "deployment": deployment,
    }
