/**
 * Member 3 — Execution Engine (Parent Agent)
 *
 * Stage-2 agent: runs AFTER the 6 research agents complete.
 * Fans out to 3 sub-agents in parallel via Promise.allSettled:
 *   1. Content Agent     — campaign brief + copy angles
 *   2. A/B Variant Agent — 3 variants, each with a falsifiable hypothesis
 *   3. Outreach Formatter — humanised email/LinkedIn sequences + deployment timeline
 *
 * Returns a single ExecutionPlanOutput that renders as an ExecutionPlan card.
 */

import type {
  AgentConfig,
  AgentContext,
  AgentOutput,
  AgentSource,
  CampaignVariant,
  ExecutionPlanOutput,
  ConfidenceLevel,
} from '../types';
import { scoreToLevel } from '../types';
import { runContentAgent } from './content-agent';
import { runABVariantAgent } from './ab-variant-agent';
import { runOutreachFormatter } from './outreach-formatter';
import { enforceExecutionGrounding } from './grounding';

function dedupeStrings(values: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const value of values) {
    const normalized = value.toLowerCase().replace(/\s+/g, ' ').trim();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    out.push(value.trim());
  }
  return out;
}

async function run(ctx: AgentContext): Promise<AgentOutput> {
  const { researchOutputs = [] } = ctx;

  // Serialize research findings so all 3 sub-agents share the same grounding context
  const groundingContext = researchOutputs.length > 0
    ? researchOutputs
        .map(o => `[${o.domain.toUpperCase()}]\nFACTS: ${o.facts.slice(0, 4).join(' | ')}\nINTERPRETATION: ${o.interpretation.slice(0, 2).join(' | ')}`)
        .join('\n\n')
    : '';

  const enrichedCtx: AgentContext = {
    ...ctx,
    priorContext: [ctx.priorContext, groundingContext].filter(Boolean).join('\n\n---\n'),
  };

  // ── Fan out 3 sub-agents in parallel ─────────────────────────────────────
  const [contentResult, variantResult] = await Promise.allSettled([
    runContentAgent(enrichedCtx),
    runABVariantAgent(enrichedCtx),
  ]);

  // Extract variants from AB agent (needed by Outreach Formatter)
  const inputVariants: CampaignVariant[] =
    variantResult.status === 'fulfilled' ? variantResult.value.variants : [];

  // Run Outreach Formatter with variants as input
  const outreachResult = await runOutreachFormatter(enrichedCtx, inputVariants).catch(() => null);

  // ── Merge all sources ─────────────────────────────────────────────────────
  const allSources: AgentSource[] = [
    ...(contentResult.status === 'fulfilled' ? contentResult.value.sources : []),
    ...(variantResult.status === 'fulfilled' ? variantResult.value.sources : []),
    ...(outreachResult ? outreachResult.sources : []),
  ].filter((s, i, a) => s.url && a.findIndex(x => x.url === s.url) === i);  // dedupe

  // ── Merge facts + interpretation ──────────────────────────────────────────
  const allFacts = dedupeStrings([
    ...(contentResult.status === 'fulfilled' ? contentResult.value.facts : []),
    ...(variantResult.status === 'fulfilled' ? variantResult.value.facts : []),
  ]).slice(0, 6);

  const allInterpretation = dedupeStrings([
    ...(contentResult.status === 'fulfilled' ? contentResult.value.interpretation : []),
    ...(variantResult.status === 'fulfilled' ? variantResult.value.interpretation : []),
  ]).slice(0, 4);

  // ── Aggregate confidence (average of successful sub-agents) ──────────────
  const scores = [
    contentResult.status === 'fulfilled' ? contentResult.value.confidenceScore : null,
    variantResult.status === 'fulfilled' ? variantResult.value.confidenceScore : null,
    outreachResult ? outreachResult.confidenceScore : null,
  ].filter((s): s is number => s !== null);

  const avgScore = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0.4;
  const confidence: ConfidenceLevel = scoreToLevel(avgScore);

  // ── Build final output ────────────────────────────────────────────────────
  const brief = contentResult.status === 'fulfilled'
    ? contentResult.value.brief
    : {
        objective: `Campaign for ${ctx.product}`,
        targetAudience: 'VP Sales / Head of Growth at Series B+ SaaS',
        painPoints: [],
        keyMessagingAngles: [],
        variantsSummary: 'Variants generated by A/B agent',
        channelStrategy: 'Cold email + LinkedIn',
        successMetrics: ['reply rate > 4%'],
        nextSteps: ['Run A/B test', 'Analyse reply sentiment after 72h'],
      };

  const mergedVariants: CampaignVariant[] = outreachResult?.enrichedVariants?.length
    ? outreachResult.enrichedVariants
    : inputVariants;
  const variants = enforceExecutionGrounding(mergedVariants, researchOutputs, ctx.product);

  const deployment = outreachResult?.deployment ?? [];

  const output: ExecutionPlanOutput = {
    agentId: 'execution-engine',
    domain: 'execution-engine',
    artifactType: 'execution-plan',
    confidence,
    confidenceScore: avgScore,
    facts: allFacts,
    interpretation: allInterpretation,
    sources: allSources,
    generatedAt: new Date().toISOString(),
    variants,
    brief,
    deployment,
  };

  return output;
}

export const executionEngineAgent: AgentConfig = {
  id: 'execution-engine',
  name: 'Execution Engine',
  description: 'Converts research findings into shipped campaigns: campaign brief, A/B variants (each with a falsifiable hypothesis), humanised outreach sequences, and deployment timeline.',
  run,
};
