#!/usr/bin/env bash
# =============================================================================
# MiroFish Live VPS Setup — 168.144.36.78
# =============================================================================
# Run this ONCE on the VPS as root or a sudo user:
#   bash vps-setup.sh
#
# What it does:
#   1. Hardens the VPS (UFW firewall, swap)
#   2. Installs Docker + Compose plugin
#   3. Clones the MiroFish repo
#   4. Creates a minimal .env with your API keys
#   5. Starts the MiroFish backend via docker compose
#   6. Prints the bootstrap command to run from your local machine
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Config — edit these before running ────────────────────────────────────────
MIROFISH_REPO="https://github.com/666ghj/MiroFish.git"
INSTALL_DIR="/opt/mirofish"
VPS_IP="168.144.36.78"
VPS_PORT="5001"

# API keys — FILL THESE IN before running the script
# LLM_API_KEY: Groq key (https://console.groq.com) — use llama-3.1-8b-instant for lower TPM
# ZEP_API_KEY: Zep memory key (https://www.getzep.com)
LLM_API_KEY="${LLM_API_KEY:-REPLACE_WITH_GROQ_KEY}"
ZEP_API_KEY="${ZEP_API_KEY:-REPLACE_WITH_ZEP_KEY}"
# Model — use smaller model to avoid TPM limits on free Groq tier
LLM_MODEL="${LLM_MODEL:-llama-3.1-8b-instant}"

# ── Pre-flight check ─────────────────────────────────────────────────────────
info "MiroFish Live VPS Setup starting on ${VPS_IP}"
[[ "$LLM_API_KEY" == "REPLACE_WITH_GROQ_KEY" ]] && warn "LLM_API_KEY not set — edit the script before running!"
[[ "$ZEP_API_KEY" == "REPLACE_WITH_ZEP_KEY" ]]  && warn "ZEP_API_KEY not set — edit the script before running!"

# ── 1. System update + basic packages ────────────────────────────────────────
info "1/6 Updating system packages…"
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl gnupg git ufw \
  debian-keyring debian-archive-keyring apt-transport-https

# ── 2. Swap (4 GB VPS needs swap for LLM workloads) ──────────────────────────
if ! swapon --show | grep -q /swapfile; then
  info "Creating 2 GB swap file…"
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
  info "Swap created."
else
  info "Swap already present — skipping."
fi

# ── 3. UFW firewall ───────────────────────────────────────────────────────────
info "2/6 Configuring UFW firewall…"
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow "${VPS_PORT}/tcp"   # MiroFish API
# If you add Caddy HTTPS later:
# ufw allow 80/tcp
# ufw allow 443/tcp
ufw --force enable
info "UFW enabled. Open ports: SSH + ${VPS_PORT}."

# ── 4. Docker ─────────────────────────────────────────────────────────────────
info "3/6 Installing Docker + Compose plugin…"
if ! command -v docker &>/dev/null; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq \
    docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
  # Allow current user to use docker without sudo
  if [ -n "${SUDO_USER:-}" ]; then
    usermod -aG docker "$SUDO_USER"
    info "Added $SUDO_USER to docker group. Log out and back in for this to take effect."
  fi
  info "Docker installed: $(docker --version)"
else
  info "Docker already installed: $(docker --version)"
fi

# ── 5. Clone MiroFish ─────────────────────────────────────────────────────────
info "4/6 Cloning MiroFish repo → ${INSTALL_DIR}…"
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Repo already exists — pulling latest…"
  git -C "$INSTALL_DIR" pull --ff-only
else
  git clone "$MIROFISH_REPO" "$INSTALL_DIR"
fi

# ── 6. Write .env ─────────────────────────────────────────────────────────────
info "5/6 Writing ${INSTALL_DIR}/.env…"
cat > "${INSTALL_DIR}/.env" <<EOF
# MiroFish Live VPS — auto-generated by vps-setup.sh

# LLM backend (Groq)
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL}
LLM_BASE_URL=https://api.groq.com/openai/v1

# Zep memory
ZEP_API_KEY=${ZEP_API_KEY}

# Flask API port
PORT=${VPS_PORT}
HOST=0.0.0.0

# Redis (used internally — docker compose supplies it)
REDIS_URL=redis://redis:6379/0
EOF
info ".env written."

# Merge with existing .env.example from the repo if it exists
if [ -f "${INSTALL_DIR}/.env.example" ]; then
  info "Merging any additional keys from .env.example…"
  # Add any missing keys from .env.example that aren't already in .env
  while IFS= read -r line; do
    key="${line%%=*}"
    if [[ "$line" =~ ^[A-Z] ]] && ! grep -q "^${key}=" "${INSTALL_DIR}/.env"; then
      echo "$line" >> "${INSTALL_DIR}/.env"
    fi
  done < "${INSTALL_DIR}/.env.example"
fi

# ── 7. Start MiroFish ─────────────────────────────────────────────────────────
info "6/6 Starting MiroFish via docker compose…"
cd "$INSTALL_DIR"

# Add restart policies to ensure containers survive reboots
# If docker-compose.yml already has restart: unless-stopped skip this
if ! grep -q 'restart:' docker-compose.yml 2>/dev/null; then
  warn "docker-compose.yml does not have restart policies. Consider adding 'restart: unless-stopped' to each service."
fi

docker compose pull --quiet || warn "docker compose pull failed — using cached images"
docker compose up -d

# Wait a few seconds then check
sleep 6
if docker compose ps | grep -q "Up"; then
  info "MiroFish containers are running:"
  docker compose ps
else
  error "Containers failed to start. Check: docker compose logs"
fi

# ── Health check ─────────────────────────────────────────────────────────────
info "Waiting for API to become available on port ${VPS_PORT}…"
for i in $(seq 1 20); do
  if curl -sf "http://localhost:${VPS_PORT}/api/graph/project/list" &>/dev/null; then
    info "MiroFish API is UP at http://${VPS_IP}:${VPS_PORT}"
    break
  fi
  sleep 3
  if [ "$i" -eq 20 ]; then
    warn "API did not respond after 60s. Check logs: docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
  fi
done

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
echo "  MiroFish Live VPS setup complete!"
echo "  API endpoint: http://${VPS_IP}:${VPS_PORT}"
echo ""
echo "  Next steps (run from your LOCAL machine):"
echo ""
echo "  1. Bootstrap a simulation:"
echo "     \$env:MIROFISH_LIVE_BASE_URL='http://${VPS_IP}:${VPS_PORT}'"
echo "     npx tsx scripts/mirofish-bootstrap.ts"
echo ""
echo "  2. Copy the printed MIROFISH_LIVE_SIMULATIONS line into .env.local"
echo ""
echo "  3. Update Vercel env vars:"
echo "     MIROFISH_LIVE_BASE_URL = http://${VPS_IP}:${VPS_PORT}"
echo "     MIROFISH_LIVE_SIMULATIONS = <output from step 1>"
echo ""
echo "  4. Monitor VPS logs:"
echo "     ssh root@${VPS_IP} 'cd ${INSTALL_DIR} && docker compose logs -f'"
echo "================================================================"
